apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: mae-demo
  namespace: mae
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: mae-demo
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: "java"
    workload-intent: code-analysis
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: buildServiceBindings
    value:
    - kind: Secret
      name: maven-settings
  - name: gitops_server_address
    value: ssh://git@github.com
  - name: gitops_ssh_secret
    value: gitops-ssh
  - name: gitops_repository_owner
    value: Mpluya
  - name: gitops_repository_name
    value: config-polaris-demo
  - name: gitops_branch
    value: main
  source:
    git:
      url: https://github.com/Mpluya/mae-demo
      ref:
        branch: main
